pipeline:
  name: newpipeline
  identifier: newpipeline
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    test: test
  stages:
    - stage:
        name: one
        identifier: one
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: |-
                          echo <+secrets.getValue("servicenow")>
                          echo "hello"
                          echo <+secrets.getValue('service<+<+pipeline.variables.hh>.toLowerCase()>w')>
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
          environment:
            environmentRef: <+input>
            deployToAll: false
            environmentInputs: <+input>
            infrastructureDefinitions: <+input>
        tags: {}
    - stage:
        name: test
        identifier: test
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: K8new
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: ECS_INFRA
            environmentInputs:
              variables:
                - name: dbname
                  type: String
                  value: <+input>
            deployToAll: false
            infrastructureDefinitions:
              - identifier: two
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
  variables:
    - name: hh
      type: String
      description: ""
      required: false
      value: "no"
  notificationRules:
    - name: dff
      identifier: dff
      pipelineEvents:
        - type: PipelineStart
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: <+variables.notification-hh>
      enabled: true
