pipeline:
  name: newpipeline
  identifier: newpipeline
  projectIdentifier: CSETest1
  orgIdentifier: AbhiOrg
  tags:
    test: test
  stages:
    - stage:
        name: custome
        identifier: custome
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: "customIamRolePoliciesNames: <+expression.isResolved(<+serviceVariables.iamRole>)?\"[]\":(expression.isResolved(<+serviceVariables.customIamRolePolicyNames>)?<+serviceVariables.customIamRolePolicyNames>:\"[]\")>"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
  variables:
    - name: hh
      type: String
      description: ""
      required: false
      value: "no"
  notificationRules:
    - name: dff
      identifier: dff
      pipelineEvents:
        - type: PipelineStart
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: <+variables.notification-hh>
      enabled: true
